---
- debug: 
    msg: 'Preparing the base host for installation of the Ghost Platform'
  tags: base_system
  
- name: 'Setting the system hostname'
  hostname:
    name: '{{ host_fqdn }}'
  tags: base_system

- name: 'Ensure sudo group exists'
  group:
     name: '{{ sudo_group }}'
     state: present
  tags: base_system

- name: 'Setting the root password for the system'
  user:
    name: root
    password: '{{ root_pass }}'
    update_password: always
    state: present

- name: 'Add Linux users to the system'
  user: 
    name: '{{ item.user_name }}'
    uid: '{{ item.uid }}'
    groups: '{{ sudo_group }}'
    append: yes
    shell: /bin/bash
    password: '{{ user_pass }}'
    update_password: always
    state: present 
  loop: '{{ user_list }}'

- name: 'Ensure /etc/sudoers.d directory exists' 
  file: 
     path: /etc/sudoers.d
     state: directory
     owner: root
     group: root
     mode: 0750

- name: 'Copy sudo file from template'
  template: 
     src: templates/extra_sudo_users.j2
     dest: /etc/sudoers.d/extra-sudo-users
     owner: root
     group: root
     mode: 0440
