---
- name: Setting custom repositories for Centos '{{ rhel_release_ver }}'
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    baseurl: '{{ item.base_url }}'
    gpgcheck: '{{ item.gpg_key_enabled }}'
    gpgkey: '{{ item.gpg_key_url }}'
    enabled: '{{ item.is_enabled }}'
  loop: '{{ custom_yum_repositories }}'
  tags: requisites
    
- name: Configuring the NodeJS repositories
  shell: >
    curl -sL '{{ ghost_node_repo_url }}' | sudo bash -
  tags: requisites

- name: Updating all installed packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  register: is_updated
  tags: requisites

- name: Rebooting after updates
  shell: > 
    sleep 5 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: is_updated is changed
  tags: requisites

- name: Waiting for host to become responsive
  wait_for_connection:
    connect_timeout: 30
    sleep: 5
    delay: 60
    timeout: 300 
  when: is_updated is changed
  tags: requisites

- name: Installing the Ghost platform requisite packages
  dnf:
    name: '{{ ghost_required_packages }}'
    state: latest
  tags: requisites
