---
- name: 'Creating Ghost installation directories'
  file:
    path: '{{ ghost_install_dir }}'
    mode: 0755
    state: directory
    owner: '{{ ghost_user }}'
    group: '{{ ghost_group }}'
  tags: ghost-prepare

- name: 'Ensure SELinux policy for Nginx'
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags: ghost-prepare

- name: 'Ensure correct SELinux context on the /var/www directories' 
  sefcontext:
    target: '/var/www/(/.*)?'
    setype: httpd_sys_content_t
    state: present
  tags: ghost-prepare

- name: 'Apply SELinux file context to the /var/www directory'
  shell: >
    restorecon -irv /var/www
  tags: ghost-prepare

- name: 'Secure MariaDB: Set root password to vaulted password'
  mysql_user: 
    name: root
    password: '{{ root_mysql_pass }}'
    host: '{{ item }}'
    state: present 
    check_implicit_admin: yes
    login_user: root
    login_password: '{{ root_mysql_pass }}'
    login_host: '{{ ghost_db_host }}'
  loop: 
    - 127.0.0.1
    - localhost
  tags: ghost-prepare

- name:  'Secure MariaDB: Remove root remote access'
  mysql_user: 
    name: root
    host: '{{ item }}'
    state: absent
    login_user: root
    login_password: '{{ root_mysql_pass }}'
    login_host: '{{ ghost_db_host }}'
  loop: 
    - '%'    
    - '::1'
    - '{{ host_fqdn }}'
  tags: ghost-prepare

- name: 'Secure MariaDB: Remove unused accounts'
  mysql_user: 
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: '{{ root_mysql_pass }}'
    login_host: '{{ ghost_db_host }}'
  tags: ghost-prepare
    
- name: 'Create the ghost database'
  mysql_db:
    name: '{{ ghost_db_name }}'
    state: present 
    login_user: root
    login_password: '{{ root_mysql_pass }}'
    login_host: '{{ ghost_db_host }}'
  tags: ghost-prepare
 
- name: 'Set MySQL password for the Ghost user: {{ ghost_user }}'
  mysql_user: 
    name: '{{ ghost_user }}'
    password: '{{ ghost_mysql_pass }}'
    login_user: root
    login_password: '{{ root_mysql_pass }}'
    login_host: '{{ ghost_db_host }}'
    priv: '{{ ghost_db_name }}.*:ALL'
    state: present 
  loop: 
    - 127.0.0.1
    - localhost
  tags: ghost-prepare

- name: 'Copy the SSL certificates for {{ ghost_site_fqdn }} to host destination location'
  copy:
    content: '{{ item.content }}'
    dest: '{{ item.location }}/{{ item.name }}'
    owner: root
    group: root
    mode: 0644
  loop: '{{ certificates }}'
  when: ghost_enable_ssl == True
  notify: restart_nginx
  tags: ghost-prepare

- name: 'Set up Ghost Nginx configuration file'
  template:
    src: templates/nginx_ghost.conf.j2
    dest: /etc/nginx/conf.d/nginx_ghost.conf
    owner: root
    group: root
    mode: 0440 
  notify: restart_nginx
  tags: ghost-prepare

- name: 'Install the ghost-cli via the npm package manager'
  npm:
    name: ghost-cli
    global: yes
    state: latest
  tags: ghost-prepare

- name: 'Ensure base web services started'
  service:
    name: nginx
    state: started 
  loop:
    - nginx
    - mariadb
  tags: ghost-prepare