---
- name: restart_chrony
  service:
     name: chronyd
     state: restarted 

- name: restart_nginx
  service:
     name: nginx
     state: restarted 

- name: restart_firewalld
  service:
     name: firewalld
     state: restarted 
