---
# default  vars file for install-ghost
#

# host specific variables
host_fqdn: blog.bertoknows.com
time_servers:
   - clock.nyc.he.net
   - clock.fmt.he.net

sudo_group_name: sudo
user_list:
  - user_name: gizzy
    user_group: gizzy
    
ghost_required_packages:
  - mariadb-server
  - nodejs
  - nginx
  - firewalld
  - python3-PyMySQL

ghost_firewall_ports:
  - port: 22
    proto: tcp
  - port: 80
    proto: tcp
  - port: 443
    proto: tcp

# yum repositories parameters
rhel_release_ver: 8
custom_yum_repositories:
  - name: 'Nginx Repo-$releasever'
    description: 'Nginx Repository for Centos ${{ rhel_release_ver }}'
    is_enabled: yes
    gpg_key_enabled: yes
    base_url: 'http://nginx.org/packages/centos/$releasever/$basearch/'
    gpg_key_url: 'https://nginx.org/keys/nginx_signing.key'

# Ghost application specific parameters
ghost_node_repo_url: 'https://rpm.nodesource.com/setup_14.x'
ghost_backend_port: 2368
ghost_site_fqdn: blog.bertoknows.com
ghost_user: gizzy
ghost_group: gizzy
ghost_db_name: ghost_blog
ghost_db_host: localhost
ghost_install_dir: /var/www/ghost
ghost_enable_ssl: true
