---
# default variables  for openstack-vm-deploy
#

# cloud used for authentication
# ~/.config/openstack/clouds.yaml
osp_cloud: dreamhost-iad

# domain for the virtual machine fqdn
vm_server_domain: holaehlo.net

# virtual machine details
osp_vm_server_name: ghostdev
osp_vm_glance_image: centos-8-arl
osp_vm_ssh_key: win-ws-key
osp_vm_flavor: gp1.lightspeed
osp_vm_security_groups: 
  - allow_ssh
  - allow_web
osp_vm_neutron_network: public

# ipa server details
# ipa records name and record values
# are retrieved from the osp_vm_server_name
# and from the dynamically assigned ip address
# ipa_admin_user and ipa_admin_password
# are encrypted in the vault variable file
create_ipa_dns_records: True
ipa_host: idm-a.voltron.xyz
ipa_zone_name: '{{ vm_server_domain }}'
ipa_dns_record_type: 'A'
